### ISSUE TITLE
Add additional columns to the Department table

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#379]
- [x] Replace median base pay with median total pay
- [x] Add total base pay
- [x] Add total extra pay
- [x] Add total expenditure

![Screen Shot 2020-02-24 at 11.59.41 AM.png](https://images.zenhubusercontent.com/5b0dc8d3348b7966b4340de0/30587235-d518-4302-be14-5f6c6d7ca524)

**Comment by fatima3558** [comment]
current columns: dept, # employees, median salary, total expenditure
needed columns: dept, # employees, median total pay, total base pay, total extra pay, total expenditure
**columns to get: median tp, total bp, total ep** --> salary related

**Comment by fatima3558** [comment]
- get all salaries where parent.id = self.object.id but NOT where id = self.object.id
- group by dept (django ORM research), order by total exp

**Comment by fatima3558** [comment]
salary__job__position__employer

**Comment by fatima3558** [comment]
currently, `aggregate_department_statistics` method gets the necessary info for the table as it is now.

```sql
SELECT
              employer.name,
              AVG(salary.amount) AS average,
              SUM(salary.amount) AS budget,
              COUNT(*) AS headcount,
              employer.slug AS slug
            {from_clause}
            WHERE employer.parent_id = {id}
            GROUP BY employer.id, employer.name
            ORDER BY SUM(salary.amount) DESC
```

**Comment by fatima3558** [comment]
@hancush Here's my initial idea for how to tackle this issue:

- The new data we need to get for the updated table is all around salaries, so writing one query for the Salary model is a good place to start
- In order to get the information we need, we would use [aggregate](https://docs.djangoproject.com/en/3.0/ref/models/expressions/#aggregate-expressions) on the Salary objects. Aggregate would also allow us to group by department 
- In this query, we would want to use the [`select_related`](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#select-related) django ORM method to get the necessary Employer info using this set of foreign key relationships: salary__job__position__employer
- this single query should allow us to get all the necessary info -- the data from `aggregate_dept_stats` will be part of the query through our use of the `select_related` method, and accessing the salary objects will give us access to the necessary salary data by using `aggregate`

Are there any weirdnesses I haven't considered? Looking forward to your feedback!

**Comment by hancush** [comment]
@fatima3558 Interesting! I hadn't considered trying to get at this through the Salary model. A couple of questions:

- You can use aggregate functions to `annotate` or `aggregate` a queryset. Which are you proposing?
- Will the result of the single query be in a similar format to the existing `aggregate_department_statistics` query, i.e., an iterable of departments with metadata?
- Are there advantages to working from the Salary vs. working from the Employer, as you did in the `get_entity_payroll` method? 

    https://github.com/datamade/bga-payroll/blob/1a1d3d27c9022d290ec527363eda186f6ad78d23/payroll/views.py#L97-L110

**Comment by fatima3558** [comment]
Thanks again for your questions, @hancush ! They help me make more sense of what I was doing before, and get a little clearer on what I intended. 

- After doing a bit more research, I found this [article](https://simpleisbetterthancomplex.com/tutorial/2016/12/06/how-to-create-group-by-queries.html) that suggests that annotate, combined with [`values`](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#values), might be better than aggregate. `values` returns a QuerySet that returns a list of dictionaries, which also seems like it could be helpful as far as maintaining the iterable within `aggregate_dept_stats()`. 

- After failing to make sense of what I was thinking yesterday, I went back and tried to figure out a query that would make sense starting from the Employer model. I think this makes more sense, and it would make it more efficient to write since the work we have done in calculating `median_total_pay`, `total_base_pay`, etc has already been done by starting from the Employer model. Also, it would make it simpler to get the headcount and name for each department.

All that said, here's the pseudocode:
```python
# the below variables are taken from `get_entity_payroll()` and `median_entity_salary()`
entity_base_pay = Sum(Coalesce(salary amount))
entity_extra_pay = Sum(Coalesce(salary extra_pay))
median_total_pay = Percent(
    NullIf(Coalesce(salary amount) + 
    Coalesce(salary extra_pay), 0). ...)

Employer.filter(parent.id=self.id)
.values(name) # this would group by department name
.annotate(
    headcount, 
    median_tp=median_total_pay, 
    entity_bp=entity_base_pay, 
    entity_ep=entity_extra_pay, 
    total_expenditure=entity_bp + entity_ep)
```

I believe this will get us all the info we need in one fell swoop.

**Comment by fatima3558** [comment]
Updated to include an `order_by`:
```python
# the below variables are taken from `get_entity_payroll()` and `median_entity_salary()`
entity_base_pay = Sum(Coalesce(salary amount))
entity_extra_pay = Sum(Coalesce(salary extra_pay))
median_total_pay = Percent(
    NullIf(Coalesce(salary amount) + 
    Coalesce(salary extra_pay), 0). ...)

Employer.filter(parent.id=self.id)
.values(name) # this would group by department name
.annotate(
    headcount, 
    median_tp=median_total_pay, 
    entity_bp=entity_base_pay, 
    entity_ep=entity_extra_pay, 
    total_expenditure=entity_bp + entity_ep)
.order_by(total_expenditure)
```

**Comment by hancush** [comment]
This approach makes a lot of sense to me, @fatima3558! I say go for it.
