### ISSUE TITLE
School data blank for 2018

### ISSUE THREAD

**Issue by deraj1013** [datamade/bga-payroll#464]
The summary portion of the page for every school in 2018 is blank. You can read it in 2017. https://bga-payroll.datamade.us/unit/lincoln-esd-27-c02d53d1/

It looks like the 2018 school year data is missing a department description. Some districts had teachers assigned to a school (which was their dept) in 2017, but that data was not provided in 2018.

**Comment by hancush** [comment]
Hey, @deraj1013, this has to do with classification. It looks like the school districts weren't auto-classified because our import looks for the "ISBE" responding agency, but the schools have a responding agency of "ISBE/All Elementary/High School Employees" in the latest data. 

Is it safe to assume that all units with a responding agency ID of 45, or "ISBE/All Elementary/High School Employees", are school districts? If so, I can go ahead and update them in bulk to avoid reupload/manual classification – and I can also update the code, so it will do the right thing moving forward.

Let me know!

**Comment by deraj1013** [comment]
The only one where that would not be the case is the agency ISBE itself (though it would hardly be a crushing defeat if this were coded as a school district since it's a school administrative body).

**Comment by hancush** [comment]
Classified school districts. For my own reference, here's what I did:

```python
from data_import.models import *
from payroll.models import *

isbe = RespondingAgency.objects.get(name='ISBE/All Elementary/High School Employees')
school_district = EmployerTaxonomy.objects.get(entity_type='School District', chicago=False)

isbe_reported = Unit.objects.filter(responding_agencies__responding_agency=isbe)

for unit in isbe_reported:
    unit.taxonomy = school_district

Unit.objects.bulk_update(isbe_reported, ['taxonomy'])
```

Reindexing units now so the proper taxonomy will show up in search!

**Comment by hancush** [comment]
Behold, school districts now have a description! Look ok to you, @deraj1013?
