### ISSUE TITLE
Sam gets app set up for local development (but without building the database)

### ISSUE THREAD

**Issue by fgregg** [datamade/bga-payroll#512]
Go through step 2 in the README: https://github.com/datamade/bga-payroll#getting-started

**Comment by smcalilly** [comment]
@fgregg I got through step 2. Had a couple of hiccups when trying to run `docker-compose up -d --build`, but I worked through them.

Extra things i had to do:
- Copy `local-settings.example.py` to `local-settings.py`
- Add `POSTGRES_PASSWORD=password` as a postgres environment variable in `docker-compose.yml`. I did this because the app wasn't detecting the password I [set in the local-settings.py file](https://github.com/datamade/bga-payroll/blob/78aea94ef7c71db923d41a66684c323ee022682d/bga_database/local_settings.py.example#L16).
- `docker-compose run --rm app python manage.py migrate` once the app was built

Does any of that seem wrong?

**Comment by hancush** [comment]
@smcalilly Pinch hitting here, since @fgregg is out for the afternoon.

> Copy local-settings.example.py to local-settings.py

Reasonable! 

> Add POSTGRES_PASSWORD=password as a postgres environment variable in docker-compose.yml. I did this because the app wasn't detecting the password I set in the local-settings.py file.

Also reasonable, and I have no idea how I was running the Postgres container without specifying a password, as [it's required by the Postgres image](https://hub.docker.com/_/postgres). 🥴 

> docker-compose run --rm app python manage.py migrate once the app was built

Strictly speaking, the migrations should run via the `migration` service when you do `docker-compose up`, but we've had issues with race conditions in the past, which might have been at play here.

Could you add your additional steps to the README, and submit a PR with the updates?

**Comment by smcalilly** [comment]
Yep! @hancush
