### ISSUE TITLE
Eternal load

### ISSUE THREAD

**Issue by deraj1013** [datamade/bga-payroll#559]
This is similar to a problem I identified with Downers Grove. Hannah identified it as a Java bug. Unsure if this is the same issue, but it looks similar for DeWitt County. https://bga-payroll.datamade.us/unit/dewitt-county-b62bdd5d/?data_year=201
<img width="860" alt="Screen Shot 2021-11-04 at 10 22 44 AM" src="https://user-images.githubusercontent.com/30843180/140350309-5124f11c-3d39-44e7-bda8-3bcb71f8299e.png">
9

**Comment by deraj1013** [comment]
Having trouble searching a few agencies ... these things could be related. I'll pull my foot off the gas and go back in a few hours.

**Comment by deraj1013** [comment]
Other weird index issues. Can't view any individual Forest View employees. https://bga-payroll.datamade.us/search/?entity_type=person&employer=forest-view-25cd0828&year=2019

**Comment by hancush** [comment]
@deraj1013 The index issues are separate from this. It looks like the staging site is having some responsiveness issues preventing the search index from rebuilding properly. I can address the endless loading today but may have to look at indexing tomorrow. I will open a separate issue.

**Comment by hancush** [comment]
The root of this issue is that we updated the FOIA source mapping with after the initial 2019 import. If we amended data associated with one of the responding agencies that changed, the import created a second unit-responding agency relationship. The app assumes there is only one responding agency associated with a given unit per year, so this second relationship created errors.

I have gone in and manually removed outdated responding agencies for units that were amended in the most recent amendment. Summary of updates:

| Unit | Old responding agency | New responding agency |
| - | - | - |
| DeKalb                           | Dekalb | DeKalb |
| Lake in the Hills                | Lake In The Hills | Lake in the Hills |
| DeKalb County                    | Dekalb County | DeKalb County |
| DeWitt County                    | Dewitt County | DeWitt County |
| Illinois                         | Will County Forest Preserve | Illinois |
| Lan-Oak Park District            | Lan Oak Park District | Lan-Oak Park District |
| City of Chicago                  | Chicago | City of Chicago |
| City Colleges of Chicago         | City Colleges Of Chicago | City Colleges of Chicago |
| Fox River Grove FPD              | Fox River Grove Fire Protection District | Fox River Grove FPD |
| LaSalle                          | Lasalle | LaSalle |
| LaSalle County                   | Lasalle County | LaSalle County |
| Oakbrook                         | Oak Brook | Oakbrook |
| Fairmont City                    | Fairmont | Fairmont City |
| Illinois Community College Board | Illinois Community College Board | Illinois Community Colleges Board |
| Carpentersville Countryside FPD  | Carpentersville Countryside | Carpentersville Countryside FPD |

@deraj1013 If you added raw data for 2019 for any of the _old_ responding agencies, you'll need to re-add it to the new ones. Raw data associated with the old agencies for past years should not be affected.

**Comment by hancush** [comment]
P.s., DeWitt County is loading now: https://bga-payroll.datamade.us/unit/dewitt-county-b62bdd5d/?data_year=2019

**Comment by deraj1013** [comment]
Thanks for the update. All of the agencies function on the dev site, but there appear to be two 2019 options in the dropdown for DeWitt County. Might be a cache issue on my end.
<img width="1173" alt="Screen Shot 2021-11-04 at 3 40 01 PM" src="https://user-images.githubusercontent.com/30843180/140416878-b8d80572-2b49-470a-b56a-0639d1e3c206.png">

**Comment by hancush** [comment]
Well observed. I manually cleared the cache, so your browser is holding on to an outdated version. If you hard refresh, do you see the right thing, @deraj1013?

**Comment by hancush** [comment]
You know probably better than I do how exhausting it is to be right all the time, @deraj1013! :-P
